# These are supported funding model platforms

github: #tijuks
patreon: #tijuks
open_collective: #tijuks
ko_fi: #tijuks
tidelift: #tijuks
community_bridge: #tijuks copilot cli
liberapay: #tijuks
issuehunt: #tijuks
lfx_crowdfunding: #tijuks
polar: #tijuks
buy_me_a_coffee: #tíjuks
thanks_dev: #tijuks
custom: # tijuks@github.com
